//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyCompany
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Toy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Toy()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ToyId { get; set; }
        public int PlantId { get; set; }
        public string ToyName { get; set; }
        public string ToyDetail { get; set; }
        public string Category { get; set; }
        public decimal ToyPrice { get; set; }
    
        public virtual ManufacturePlant ManufacturePlant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public void ToyList()
        {
            var dbContext = new ToyCompanyDbEntities();
            Console.WriteLine("Enter category");
            var category = Console.ReadLine();
            var toyList = dbContext.Toys.Where(t => t.Category == category);
            foreach (var list in toyList)
            {

                Console.WriteLine("Toy Id"+list.ToyId+"Toy Name :" + list.ToyName +""+ "Details: " + list.ToyDetail + "" + "Price :" + list.ToyPrice);
            }
        }
    }
}
